name: Frontend Deployment

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'apps/frontend/**'

permissions:
    id-token: write
    contents: read

jobs:
  frontend:
    name: Frontend Deployment
    runs-on: ubuntu-latest
    steps:
    
    - name: Checking code out
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{vars.AWS_REGION}}
        role-to-assume: ${{vars.AWS_ASSUME_ROLE_ARN}}
   
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: NPM Install
      working-directory: ./apps/frontend/youtube-live-app
      run: |
        npm ci --silent

    - name: NPM Build
      working-directory: ./apps/frontend/youtube-live-app
      run: |
        npm run build

    - name: S3 Upload
      working-directory: ./apps/frontend/youtube-live-app
      run: |
        aws s3 sync ./dist ${{vars.S3_BUCKET}}

    - name: Cloudfront Create Invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id ${{vars.CLOUDFRONT_DISTRIBUTION_ID}} --paths "/*"