name: Main
on:
  workflow_dispatch:
  push: 
     tags:
       - v1.**

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Autenticação Repositorio
        uses: docker/login-action@v3.4.0
        with: 
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build e Push
        uses: docker/build-push-action@v6.15.0
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_LOGIN }}/application:${{ github.ref_name }}
            ${{ secrets.DOCKER_LOGIN }}/application:latest

  CD: 
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Definindo contexto
        uses: Azure/k8s-set-context@v4.0.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Config AWS 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1


      - name: Deploy no Kubernetes
        uses: Azure/k8s-deploy@v5.0.1
        with:
          images: ${{ secrets.DOCKER_LOGIN }}/application:${{ github.ref_name }}
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
            kubernetes/secrets.yaml
            kubernetes/sa.yaml