services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # UI
      - "14268:14268" # HTTP collector (OTel)
      - "6831:6831/udp" # UDP (Thrift)
      - "9411:9411" # Zipkin compatible

  mysite:
    image: julianorib/mysite:v4.2
    container_name: mysite
    ports:
      - "8080:8080"

volumes:
  grafana-storage:


